/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksCampaignTickRouteImport } from './routes/api/public/hooks/campaign-tick'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCampaignTickRoute =
  ApiPublicHooksCampaignTickRouteImport.update({
    id: '/api/public/hooks/campaign-tick',
    path: '/api/public/hooks/campaign-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/generate': typeof GenerateRoute
  '/templates': typeof TemplatesRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/generate': typeof GenerateRoute
  '/templates': typeof TemplatesRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bulk': typeof BulkRoute
  '/contact': typeof ContactRoute
  '/generate': typeof GenerateRoute
  '/templates': typeof TemplatesRoute
  '/api/public/hooks/campaign-tick': typeof ApiPublicHooksCampaignTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bulk'
    | '/contact'
    | '/generate'
    | '/templates'
    | '/api/public/hooks/campaign-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bulk'
    | '/contact'
    | '/generate'
    | '/templates'
    | '/api/public/hooks/campaign-tick'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bulk'
    | '/contact'
    | '/generate'
    | '/templates'
    | '/api/public/hooks/campaign-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BulkRoute: typeof BulkRoute
  ContactRoute: typeof ContactRoute
  GenerateRoute: typeof GenerateRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiPublicHooksCampaignTickRoute: typeof ApiPublicHooksCampaignTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/campaign-tick': {
      id: '/api/public/hooks/campaign-tick'
      path: '/api/public/hooks/campaign-tick'
      fullPath: '/api/public/hooks/campaign-tick'
      preLoaderRoute: typeof ApiPublicHooksCampaignTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BulkRoute: BulkRoute,
  ContactRoute: ContactRoute,
  GenerateRoute: GenerateRoute,
  TemplatesRoute: TemplatesRoute,
  ApiPublicHooksCampaignTickRoute: ApiPublicHooksCampaignTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
